config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :catusers,controllers: {
    sessions: "catusers/sessions",
    registrations: "catusers/registrations"
  }

  post 'new_user_raction',  to:"reactions#new_user_reaction", as:"new_user_reaction"
   resources :comments, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :aventure
  has_many :catcomments, dependent: :destroy
  has_many :reactions, dependent: :destroy
  has_many :catuser, through: :reactions


  Kinds = %w[like dislike not_interested neutral].freeze
KindsSpanish = {"like" => "Me gusta", "dislike" => "No me gusta",
"not_interested" => "No me interesa", "neutral" => "Neutral"}.freeze


end

app/models/aventure.rb
class Aventure < ApplicationRecord
    has_many :articles, dependent: :destroy
end

app/models/cat_comment.rb
class CatComment < ApplicationRecord
  belongs_to :article
  belongs_to :catuser
  has_many :reactions, dependent: :destroy
end

app/models/catuser.rb
class Catuser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reactions
  has_many :catcomments
  has_many :articles, through: :reactions       
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :article, optional: true
  belongs_to :catuser
  belongs_to :catcomment, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
        devise_parameter_sanitizer.permit(:account_update, keys:[:name])
    end 

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
    @cat_comment = Cat_Comment.new
    @catcomments = @article.cat_comments
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :description, :when_went, :aventure_id)
    end
end

app/controllers/catcomments_controller.rb
class CatcommentsController < ApplicationController
    before_action :set_cat_comment, only: %i[ shoe edit update destroy]

def index
  @catcomments = Cat_Comment.ApplicationController
  end

  def new
    @catcooment = Cat_Comment.new
  end

  def create
    @article = Article.find(params[:cat_comment] [:article_id])    
    @cat_comment = Cat_Comment.new(comment_params)

        @cat_comment.user = current_catuser
        respond_to do |format|
        if @cat_comment.save
        format.html { redirect_to cat_comment_url(@cat_comment), notice:
        'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @cat_comment}
        else
        format.html { render :new, status: :unprocessable_entity}
        format.json{ render json: @cat_comment.errors, status: :unprocessable_entity }
        
        end
      end
    end

    def update
      respond_to do |format|
        if @cat_comment.update(cat_comment_params)
          format.html { redirect_to comment_url(@cat_comment), notice: "Comment was successfully updated." }
          format.json { render :show, status: :ok, location: @cat_comment }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @cat_comment.errors, status: :unprocessable_entity }
        end
      end
    end


        private
        def cat_comment_params
            params.require(:cat_comment).permit(:content, :article_id)
end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    def new_user_reaction
        @catuser = current_catuser
        @type = params[:reaction_type]
        @article = Article.find(params[:article_id]) if params[:article_id]
        @catcomment = CatComment.find(params[:cat_comment_id]) if params[:cat_comment_id]
        @kind = params[:kind]
        respond_to do |format|
            (@type == "comment") ? reaction_cat_comment = Reaction.find_by(catuser_id: @catuser,
        comment_id: @cat_comment.id) : reaction_article = Reaction.find_by(catuser_id: @catuser.id,
        article_id: @article.id)
            if reaction_article || reaction_cat_comment
                format.html { redirect_to article_path(@article), notice: 'You already reacted
                to this article' }
                else
                (@type == "article") ? @reaction = Reaction.new(catuser_id: @catuser.id, article_id:
                @article.id, reaction_type: @type, kind: @kind) : @reaction = Reaction.new(catuser_id:
                @catuser.id, cat_comment_id: @cat_comment.id, reaction_type: @type, kind: @kind)
                if @reaction.save!
                format.html { redirect_to article_path(@article), notice: 'Reaction was
                successfully created.' }
                else
                format.html { redirect_to article_path(@article), notice: 'Something went
                wrong' }
                 end
               end
                end
              end
            end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/catcomments_helper.rb
module CatcommentsHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

  <p>
    <strong>Cuando fui:</strong>
    <%= article.when_went %>
  </p>

  <p>
    <strong>Aventure:</strong>
    <%= article.aventure_id %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :when_went, style: "display: block" %>
    <%= form.datetime_field :when_went %>
  </div>

  <div>
    <%= form.label :aventure_id, style: "display: block" %>
    <%= form.text_field :aventure_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>
<% render 'cat_comments/form'%>
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
  
<% Article::Kinds.each do |kind| %>
<%= button_to "#{Article::KindsSpanish[kind]}",
new_user_reaction_path(article_id: @article.id, reaction_type:
"article", kind: kind), method: :post %>
<% end %>


</div>

app/views/catcomments/_form.html.erb
<%= form_with(model: @cat_comment) do |form| %>
<% if @cat_comment.errors.any? %>
<div style= "color:red">
<h2><%= pluralize(cat_comment.errors.count, "error")%>Este comentario no se pudo crear</h2>

<ul>
<% @cat_comment.errors.each do |error|%>
<li><%=error.full_messages %></li>
<% end %>
</ul>
</div>
<% end %>

<div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_field :content %>
  </div>

  <div>
    <%= form.label :catuser_id, style: "display: block" %>
    <%= form.text_field :catuser_id %>
  </div>

  <div>
    <%= form.label :article_id, style: "display: block" %>
    <%= form.text_field :article_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crazy4Cats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar"%>
   <p class="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to "Crazy4Cats", articles_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNavDropdown">
        <ul class="navbar-nav me-auto">
            <li>
                <%= link_to "Articles", root_path, class:"nav-link" %>
            </li>
        </ul>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <% if catuser_signed_in? %>
              <% if current_catuser.name %>
                Hola <%= current_catuser.name %>
              <% else %>
                Hola <%= current_catuser.email %>
              <% end %>
            <% else %>
                Inicia sesión o registrate
            <% end %>
          </a>
          <ul class="dropdown-menu">
            <% if catuser_signed_in? %>
                <li><%= button_to "Cerrar Sesión", destroy_catuser_session_path, class:"dropdown-item", method: :delete %></li>
            <% else %>
                <li><%= link_to "Iniciar Sesión", new_catuser_session_path, class:"dropdown-item" %></li>
                <li><%= link_to "Registro", new_catuser_registration_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>